class CursesClues:
    black_eyes = "eyes - black"
    red_eyes = "eyes - red"
    white_eyes = "eyes - white"
    black_goo = "black goo"
    missing_or_dead_people_regularly_in_the_same_area = "groups of people missing/dead regularly in the same area"
    missing_or_dead_people_in_similar_way_randomly_across_time_in_the_same_area = \
        "missing or dead people in similar way randomly across time in the same area"
    missing_heart = "missing heart"
    people_dead_weirdly = "people dead weirdly"
    people_acting_weirdly = "people acting weirdly"
    people_feeling_weird_or_bad = "people feeling weird or bad"
    people_scared_of_everything = "people scared of everything"
    people_wishes_come_true = "people wishes come true"
    people_hear_truth_only = "people hear truth only"
    people_seeing_strange_things = "people seeing strange things"
    people_seeing_things_or_figures = "people seeing things or figures (ghosts, people, reapers, beings, unicorns, " \
                                      "giant octopuses, etc.)"
    people_nightmares_come_true = "people nightmares come true"
    people_doing_what_they_are_told = "people doing what they are told"
    shadows_of_people_on_the_wall = "shadows of people on the wall"
    suicides = "suicides"
    hallucinations = "hallucinations"
    weird_animal_behavior = "weird animal behavior"
    animal_like_behavior_of_a_person = "animal like behavior of a person"
    double_tongue = "double tongue"
    cat_eyes = "cat eyes"
    claws = "claws"
    venom_necrosis = "venom necrosis"
    high_strength = "high strength"
    eats_whole_animals = "eats whole animals"
    control_over_a_reaper = "control over a reaper"
    black_altar = "black altar"
    controlled_with_a_spell_and_a_cross = "controlled with a spell and a cross"
    emf = "Electromagnetic Field"
    no_emf = "no Electromagnetic Field"
    no_cold_spots = "no cold spots"
    no_sulfur = "no sulfur"
    drawn_quincunx = "drawn quincunx"
    no_hex_bags = "no hex bags"
    hex_bag_hidden_somewhere = \
        "hex bag hidden somewhere (made with bird bones, rabbit's teeth, something that a person owned)"
    coin_hidden_somewhere = "coin hidden somewhere"
    weird_electronics_behavior = "weird electronics behavior"
    sealed_with_a_kiss = "sealed with a kiss"
    strange_different_things_happening = "strange, different things happening - like invisible people, Bigfoot, " \
                                         "large lottery wins, etc."
    magical_coin = "magical coin"
    card_found_on_a_victim = "card found on a victim"
    the_last_person_that_got_kissed_dies = "the last person that got kissed dies " \
                                           "(reverse order - first kisses, dies last)"
    slow_loss_of_the_memory = "slow loss of the memory"
    small_earth_quake = "small earth quake"
    number_of_reapers_appearing = "number of reapers appearing"
    can_switch_souls_of_people = "can switch souls of people"
    can_make_people_younger = "can make people younger"
    does_not_work_on_people_without_souls = "does not work on people without souls"
    different_history = "different history"
    different_memories = "different memories"
    weird_dreams = "weird dreams"
    strange_feeling_that_things_should_be_different = "strange feeling that things should be different"
    blinding_love = "blinding love"
    seen_as_a_clown = "seen as a clown"
    bite_marks_on_peoples_necks = "bite marks on peoples necks"
    no_bite_marks_on_peoples_necks = "no bite marks on peoples necks"
    red_blood = "red blood"
    people_appearing_out_of_nowhere = "people appearing out of nowhere"
    killed_hell_hound = "killed Hell hound"
    blood_cough = "blood cough"
    meteor_shower_over_earth = 'meteor shower over Earth'
    less_affected_by_telekinesis_of_knight_of_hell = "less affected by telekinesis of Knight of Hell"
    increased_regeneration = "increased regeneration"


class CursesDisableMethods:
    surviving_the_curse = "surviving the curse"
    destroy_the_coptic_cross = "destroy the coptic cross"
    destroy_the_black_altar = "destroy the black altar, that was made with bones and human blood"
    destroy_the_coin = "destroy the coin"
    burn_the_hex = "burn the hex"
    squeeze_the_hex = "squeeze the hex"
    magic_brew = "magic brew"
    disable_the_spirit_that_causes_it = "disable the spirit that causes it"
    first_person_that_wished_has_to_remove_the_coin = "first person that wished has to remove the coin"
    melt_the_coin = "melt the coin"
    kill_the_witch_that_cursed_a_person = "kill the Witch that cursed a person"
    kill_the_person_that_causes_it = "kill the person that causes it"
    kill_goddess_of_truth_veritas = "kill goddess of truth Veritas"
    wait_for_an_opening_from_the_other_side = "wait for an opening from the other side"
    wait_for_if_to_pass = "wait for if to pass"
    will_of_an_angel_on_soul_juice = "will of an angel on soul juice"
    age_changing_spell = "Age changing spell"
