class CursesClues:
    missing_or_dead_people_regularly_in_the_same_area = "groups of people missing/dead regularly in the same area"
    missing_or_dead_people_in_similar_way_randomly_across_time_in_the_same_area = \
        "missing or dead people in similar way randomly across time in the same area"
    people_dead_weirdly = "people dead weirdly"
    people_acting_weirdly = "people acting weirdly"
    people_feeling_weird_or_bad = "people feeling weird or bad"
    people_scared_of_everything = "people scared of everything"
    people_wishes_come_true = "people wishes come true"
    people_hear_truth_only = "people hear truth only"
    suicides = "suicides"
    hallucinations = "hallucinations"
    weird_animal_behavior = "weird animal behavior"
    control_over_a_reaper = "control over a reaper"
    black_altar = "black altar"
    controlled_with_a_spell_and_a_cross = "controlled with a spell and a cross"
    emf = "Electromagnetic Field"
    no_emf = "no Electromagnetic Field"
    no_sulfur = "no sulfur"
    drawn_quincunx = "drawn quincunx"
    no_hex_bags = "no hex bags"
    hex_bag_hidden_somewhere = \
        "hex bag hidden somewhere (made with bird bones, rabbit's teeth, something that a person owned)"
    weird_electronics_behavior = "weird electronics behavior"
    sealed_with_a_kiss = "sealed with a kiss"
    strange_different_things_happening = "strange, different things happening - like invisible people, Bigfoot, " \
                                         "large lottery wins, etc."
    magical_coin = "magical coin"
    card_found_on_a_victim = "card found on a victim"
    the_last_person_that_got_kissed_dies = "the last person that got kissed dies " \
                                           "(reverse order - first kisses, dies last)"
    slow_loss_of_the_memory = "slow loss of the memory"
    small_earth_quake = "small earth quake"
    number_of_reapers_appearing = "number of reapers appearing"
    can_switch_souls_of_people = "can switch souls of people"
    does_not_work_on_people_without_souls = "does not work on people without souls"


class CursesDisableMethods:
    surviving_the_curse = "surviving the curse"
    destroy_the_coptic_cross = "destroy the coptic cross"
    destroy_the_black_altar = "destroy the black altar, that was made with bones and human blood"
    burn_the_hex = "burn the hex"
    magic_brew = "magic brew"
    disable_the_spirit_that_causes_it = "disable the spirit that causes it"
    first_person_that_wished_has_to_remove_the_coin = "first person that wished has to remove the coin"
    melt_the_coin = "melt the coin"
    kill_the_witch_that_cursed_a_person = "kill the Witch that cursed a person"
    kill_goddess_of_truth_veritas = "kill goddess of truth Veritas"
