class MonstersClues:
    ripped_throat = "ripped throat"
    burned_eyes_of_victims = "burned eyes of victims"
    black_eyes = "eyes - black"
    red_eyes = "eyes - red"
    yellow_eyes = "eyes - yellow"
    green_eyes = "eyes - green"
    bright_eyes = "eyes - bright"
    weird_weather = "weird weather"
    weird_animal_behavior = "weird animal behavior"
    weird_things_behavior = "weird things behavior"
    weird_electronics_behavior = "weird electronics behavior"
    weird_noises = "weird noises"
    weird_fire_spontaneous_combustion = "weird fire/spontaneous combustion"
    black_blood = "blood - black"
    burned_by_holy_water = "burned by holy water"
    sulfur = "sulfur"
    triangle_wound = "victims wound shaped like triangle"
    triangle_wound_with_burns = "victims wound shaped like triangle with burns around"
    travels_as_black_fog = "travels as a black fog"
    travels_as_white_fog = "travels as a white fog"
    travels_as_red_fog = "travels as a red fog"
    travels_as_black_green_fog = "travels as a black - green fog"
    people_acting_weirdly = "people acting weirdly - like not themselves"
    people_seeing_things = "people seeing things (ghosts, etc.)"
    missing_or_dead_people_in_similar_way_randomly_across_time_in_the_same_area = \
        "people missing/dead weirdly, similarly, randomly across a time(weeks/months/years) in the same area"
    missing_or_dead_people_regularly_in_the_same_area = "groups of people missing/dead regularly in the same area"
    missing_body = "missing body"
    people_burned_on_the_ceiling = "people burned on the ceiling of their house"
    moves_fast = "moves fast"
    strange_roar = "strange roar"
    able_to_use_doors = "able to use doors"
    claws = "claws"
    mimics_human_voice = "mimics human voice"
    enormous_black_fog = "enormous black fog"
    leaves_zombie_like_people_with_black_veins_around_neck = "leaves zombie-like people with black veins around neck"
    emf = "Electromagnetic Field"
    reacts_to_gods_name_in_latin = "reacts to Gods name in latin"
    summoned_by_saying_bloody_marry_in_front_of_the_mirror = "summoned by saying Bloody Marry in front of the mirror"
    objects_seen_in_night_vision = "objects seen in night vision"
    can_take_form_of_other_people = "can take form of other people"
    can_copy_memories_of_other_people = "can copy memories of other people"
    being_at_two_places_at_once = "being at 2 places at once"
    skin_left_behind = "skin left behind"
    invisible_entity = "invisible entity"
    ozone_smell = "ozone smell"
    telekinesis = "telekinesis"
    flashing_lights = "flashing lights"
    seen_as_fire = "seen as fire"
    seen_as_a_scarecrow = "seen as a scarecrow"
    body_torn_apart = "body torn apart"
    no_blood_in_the_body = "no blood in the body"
    animal_like_attack = "animal-like attack"
    feeding_during_solar_eclipse = "feeding during the solar eclipse"
    feeding_at_night = "feeding at night"
    attacks_at_night = "attacks at night"
    feeding_on_vulnerable = "feeding on vulnerable"
    missing_heart = "missing heart"
    leaves_soulless_people_behind = "leaving soulless people behind"
    high_strength = "high strength"
    kids_imaginary_friend = "kids' imaginary friend"
    people_dead_weirdly = "people dead weirdly"
    visions = "visions"
    ghost_like_creature = "ghost-like creature"
    victims_hear_screams = "victims hear scream"
    victims_hear_children_cry = "victims hear children cry"
    victims_hear_voices = "victims hear voices"
    cold_spots = "cold spots"
    feeling_of_something_bad = "feeling of something bad"
    victims_in_coma_fading_and_dying = "victims in coma, fading and dying"
    junkless_creature = "junkless creature"
    mutant_pale_creature = "mutant pale creature"
    needle_like_teeth = "needle-like teeth"
    shining_of_magic_neckless = "shining of the magic neckless"
    bible_burns_it = "Bible burns it"
    invisible_dogs = "invisible dogs"
    goat_man = "goat-man"
    biblical_like_events = "biblical-like events (storms, diseases, plagues, power losses)"
    empty_graves = "empty graves"
    local_legend_about_somebody_killed_or_died = "local legend about somebody killed/died in the past"
    silent_area = "silent area - not even crickets are heard"
    intelligent = "intelligent"
    can_control_water = "can control water"
    psychic_abilities = "psychic abilities - knows the past, the future and the present of people or places, " \
                        "senses energies and spirits"


class MonstersKillMethods:
    decapitation = "decapitation"
    angel_blade = "angel blade"
    first_blade = "first blade"
    gold_blade = "gold blade"
    exorcism = "exorcism - The Rituale Romanum (sends a demon back to hell for good)"
    demon_killing_knife = "demon killing knife"
    holy_oil = "holy oil"
    angel_sword = "angel sword"
    colt_of_colt_with_magic_bullets = \
        "colt of Colt with magic bullets (silver bullets covered with holy oil, mirra and sage than use a spell)"
    magic_red_high_heels = "magic red high heels"
    witch_killing_brew = "witch-killing brew"
    scythe_of_death = "scythe of the death"
    burn_salted_corpse = "burn salted corpse/remains"
    destroy_the_object_that_the_ghost_is_bound_to = "destroy the object, that the ghost is bound to"
    bring_the_spirit_to_its_crime_place = "bring the spirit to its crime place - for other ghosts to kill it"
    bring_the_spirit_what_it_wants = "bring the spirit, what it wants (an object of revenge)"
    burn_it = "burn it"
    silver_bullet_into_the_heart = "silver bullet into the heart"
    # bullet_into_the_head = "bullet into the head"  ???
    angelica_root_mixture = "mixture of Angelica root, Van Van oil, dust from the crossroads and other 'odds and ends' " \
                            "put into the corners facing each world side on each floor - it purifies the haunted house"
    burn_the_sacred_tree = "burn the sacred tree"
    copper_coin_placed_under_the_tongue = "copper coin placed under the tongue"
    zanna_killing_knife = "Zanna killing knife"
    cut_thoroat = "cut throat"
    stabbing_the_heart = "stabbing the heart"
    will_of_an_archangel = "will of an archangel"
    will_of_prince_of_hell = "will of Prince of Hell"
    will_of_a_nephilim = "will of a Nephilim"
    celtic_sigil = "celtic sigil made of blood in the house and in the nest"
    the_darkness = "The Darkness"
    like_any_human = "like any human"
    lance_of_archangel_michael = "lance of Archangel Michael"


class MonstersDisableMethods:
    iron_or_iron_bullets = "iron bullets/iron in general"
    salt_or_salted_bullets = "salt/salted bullets"
    silver_or_silver_bullets = "silver/silver bullets"
    symbols_of_anasazi = "symbols of anasazi - can't cross it"
    holy_oil = "holy oil - can't cross it"
    dead_mans_blood = "dead mans blood"
    decapitation = "decapitation"
    cage_of_lucyfer_in_hell = "cage of Lucyfer in hell"
    witch_catcher = "witch-catcher"
    all_of_angels_single_blow = "all of angels single blow (release of energy)"
    celtic_imprisonment_spell = "celtic imprisonment spell"
    symbol_made_with_blood = "symbol made with blood"
    celtic_sigit_to_trap_monsters = "celtic sigit to trap monsters"
    dust_for_hell_hounds = "dust for hell hounds?"
    angel_knuckle_duster = "angel knuckle duster"


class MonstersCureMethods:
    cocktail_made_of_blood_of_the_vampire_that_bit_the_victim = \
        "cocktail made of blood of the vampire that bit the victim"
    plasma_therapy_with_the_blood_of_the_werewolf_that_bit_the_victim = \
        "plasma therapy with the blood of the werewolf that bit the victim"
