class OrganizationKnowledge:
    time_travel = "time travel"
    demon_killing_knife = "Demon-killing knife of the Kurds"
    haitian_symbol_for_speaking_to_the_dead = "haitian symbol for speaking to the dead"
    knights_of_hell = "Knights of Hell"
    golem_magic = "golem magic"
    immortal_life = "immortal life"
    drakopoolos_journal = "Drakopoolos' journal"
    summoning_of_zeus = "summoning of Zeus"
    irregular_jinns = "irregular jinns"
    demonic_possessions = "demonic possessions"
